"""Shared dataclasses and domain types used across all agents."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import pandas as pd
import numpy as np


class AgentState(str, Enum):
    """Operational states for agents."""
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    HALTED = "HALTED"


class MarketBias(str, Enum):
    """Overall directional conviction computed by technical analysis."""
    STRONG_BULLISH = "STRONG_BULLISH"
    BULLISH = "BULLISH"
    NEUTRAL = "NEUTRAL"
    BEARISH = "BEARISH"
    STRONG_BEARISH = "STRONG_BEARISH"


class PositioningQuadrant(str, Enum):
    """Classical derivatives positioning quadrant based on price and open interest changes."""
    LONG_ACCUMULATION = "LONG_ACCUMULATION"    # Price UP, OI UP (Aggressive new buyers)
    SHORT_COVERING = "SHORT_COVERING"          # Price UP, OI DOWN (Shorts buying back to exit)
    SHORT_ACCUMULATION = "SHORT_ACCUMULATION"  # Price DOWN, OI UP (Aggressive new sellers)
    LONG_LIQUIDATION = "LONG_LIQUIDATION"      # Price DOWN, OI DOWN (Longs forced out/liquidating)
    BALANCED = "BALANCED"                      # Neutral/Sideways


class CrowdingBias(str, Enum):
    """Aggregate market positioning crowding level."""
    CROWDED_LONG = "CROWDED_LONG"              # High risk of long squeeze
    BALANCED = "BALANCED"                      # Stable equilibrium
    CROWDED_SHORT = "CROWDED_SHORT"            # High risk of short squeeze


class VolatilityRegime(str, Enum):
    """Statistical market volatility regime."""
    LOW_VOL_COMPRESSION = "LOW_VOL_COMPRESSION"  # Consolidation / Pre-breakout squeeze
    TRENDING_EXPANSION = "TRENDING_EXPANSION"    # Stable directional movement, high trend edge
    HIGH_VOL_CHAOS = "HIGH_VOL_CHAOS"            # Extreme volatility spikes, liquidation wicks


@dataclass
class OHLCV:
    """Represents a single price candle."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp,
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
        }


@dataclass
class DataQualityReport:
    """Quality assessment report produced by the Data Quality Agent."""
    status: AgentState
    quality_scores: Dict[str, float]       # Per timeframe score (0.0 - 1.0)
    overall_quality: float                 # Aggregate quality score (0.0 - 1.0)
    is_tradeable: bool                     # Absolute veto flag: False = halt all trading
    freshness_ok: bool                     # True if latest candle is within tolerance
    anomalies: List[Dict[str, Any]] = field(default_factory=list)
    gaps_filled: int = 0
    warnings: List[str] = field(default_factory=list)
    data: Dict[str, pd.DataFrame] = field(default_factory=dict)
    features: Dict[str, pd.DataFrame] = field(default_factory=dict)
    latest_price: float = 0.0
    spread_pct: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class DataPacket:
    """Standardized multi-timeframe data packet delivered to trading agents."""
    symbol: str
    timeframes: Dict[str, pd.DataFrame]    # {"15m": df, "1h": df, "4h": df, "1d": df}
    features: Dict[str, pd.DataFrame]      # Derived features per timeframe
    quality: DataQualityReport
    latest_price: float = 0.0
    spread_pct: float = 0.0
    fetched_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class TechnicalAnalysisReport:
    """Standardized technical report generated by Technical Analysis Agent (Sprint 2)."""
    symbol: str
    bias: MarketBias
    confluence_score: float                # Bounded [-1.0, +1.0]
    timeframe_scores: Dict[str, float]     # Per timeframe confluence [-1.0, +1.0]
    dimension_scores: Dict[str, float]     # Trend, Momentum, Volatility, Volume
    invalidation_price: float              # Critical structural stop level
    support_levels: List[float] = field(default_factory=list)
    resistance_levels: List[float] = field(default_factory=list)
    atr_14: float = 0.0                    # 1h ATR for position sizing & stops
    target_1r: float = 0.0                 # 1.5R target price
    target_2r: float = 0.0                 # 2.5R target price
    is_macro_bull: bool = True             # True if 1h close >= 200 SMA (Institutional Macro Trend)
    macro_trend: str = "BULLISH"           # "BULLISH" or "BEARISH"
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class MarketIntelligenceReport:
    """Derivatives and macro sentiment intelligence produced by Market Intelligence Agent (Sprint 3)."""
    symbol: str
    funding_rate: float                        # Current 8h rate (e.g. 0.0001 = 0.01%)
    funding_rate_annualized: float             # Annualized percentage (e.g. 10.95%)
    funding_zscore: float                      # 30-day rolling Z-score
    open_interest_usd: float                   # Total Open Interest denominated in USD
    oi_change_4h_pct: float                    # % change in OI over past 4 hours
    oi_change_24h_pct: float                   # % change in OI over past 24 hours
    positioning_quadrant: PositioningQuadrant  # Quadrant regime classification
    top_trader_long_short_ratio: float         # Top accounts Long/Short ratio (e.g. 1.25)
    fear_and_greed_index: int                  # Macro sentiment index (0 to 100)
    fear_and_greed_label: str                  # "Extreme Fear", "Greed", etc.
    crowding_bias: CrowdingBias                # CROWDED_LONG, BALANCED, CROWDED_SHORT
    crowding_penalty: float                    # 0.0 to 0.50 (factor used to downsize or veto trade)
    squeeze_warning: Optional[str] = None      # e.g. "IMMINENT_LONG_SQUEEZE"
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class VolatilityReport:
    """Volatility and statistical regime forecast produced by Volatility & Regime Forecaster Agent (Sprint 4)."""
    symbol: str
    forecasted_volatility_24h: float           # Annualized forecasted volatility % (e.g. 52.4%)
    parkinson_volatility: float                # High-Low continuous Parkinson volatility (annualized %)
    garman_klass_volatility: float             # OHLC Garman-Klass volatility (annualized %)
    ewma_volatility: float                     # RiskMetrics EWMA volatility (annualized %)
    volatility_percentile: float               # 0 to 100 percentile rank vs lookback history
    regime: VolatilityRegime                   # LOW_VOL_COMPRESSION, TRENDING_EXPANSION, HIGH_VOL_CHAOS
    volatility_multiplier: float               # Position sizing multiplier (e.g. 0.40 to 1.30)
    atr_stop_multiplier: float                 # Dynamic ATR stop distance multiplier (e.g. 1.2 to 2.5)
    is_breakout_imminent: bool                 # True if Bollinger bandwidth and Parkinson vol are squeezed
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class StrategySpecies(str, Enum):
    """The 4 trading philosophies evolved in StrategyOne."""
    MOMENTUM_TREND = "MOMENTUM_TREND"              # SuperTrend + EMA Ribbon trend following
    MEAN_REVERSION = "MEAN_REVERSION"              # RSI + Bollinger Bands + VWAP counter-trend
    BREAKOUT_VOLATILITY = "BREAKOUT_VOLATILITY"    # Bollinger Squeeze + Volume surge expansion
    REGIME_ADAPTIVE = "REGIME_ADAPTIVE"            # Multi-agent synthesis (Confluence + Positioning + Volatility)


@dataclass
class StrategyGenome:
    """Immutable strategy DNA containing 8 core genes (alleles) and metadata."""
    strategy_id: str
    species: StrategySpecies
    entry_signal_threshold: float = 0.30       # Minimum directional confidence [0.15, 0.85]
    trend_filter_lookback: int = 50           # Moving average period for macro trend [10, 200]
    rsi_oversold_bound: float = 30.0          # Oversold bound for long entry [20.0, 40.0]
    rsi_overbought_bound: float = 70.0        # Overbought bound for short entry [60.0, 80.0]
    stop_loss_atr_mult: float = 1.8           # Stop loss distance in ATR multiples [1.0, 3.5]
    take_profit_atr_mult: float = 3.0         # Profit target distance in ATR multiples [1.5, 6.0]
    sentiment_filter_enabled: bool = True     # Whether to veto against extreme FGI / crowding
    generation: int = 0
    fitness_score: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_id": self.strategy_id,
            "species": self.species.value if isinstance(self.species, StrategySpecies) else str(self.species),
            "entry_signal_threshold": round(self.entry_signal_threshold, 4),
            "trend_filter_lookback": int(self.trend_filter_lookback),
            "rsi_oversold_bound": round(self.rsi_oversold_bound, 2),
            "rsi_overbought_bound": round(self.rsi_overbought_bound, 2),
            "stop_loss_atr_mult": round(self.stop_loss_atr_mult, 2),
            "take_profit_atr_mult": round(self.take_profit_atr_mult, 2),
            "sentiment_filter_enabled": bool(self.sentiment_filter_enabled),
            "generation": int(self.generation),
            "fitness_score": round(self.fitness_score, 4),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "StrategyGenome":
        species = data.get("species", StrategySpecies.MOMENTUM_TREND)
        if isinstance(species, str):
            species = StrategySpecies(species)
        return cls(
            strategy_id=str(data["strategy_id"]),
            species=species,
            entry_signal_threshold=float(data.get("entry_signal_threshold", 0.30)),
            trend_filter_lookback=int(data.get("trend_filter_lookback", 50)),
            rsi_oversold_bound=float(data.get("rsi_oversold_bound", 30.0)),
            rsi_overbought_bound=float(data.get("rsi_overbought_bound", 70.0)),
            stop_loss_atr_mult=float(data.get("stop_loss_atr_mult", 1.8)),
            take_profit_atr_mult=float(data.get("take_profit_atr_mult", 3.0)),
            sentiment_filter_enabled=bool(data.get("sentiment_filter_enabled", True)),
            generation=int(data.get("generation", 0)),
            fitness_score=float(data.get("fitness_score", 0.0)),
        )


@dataclass
class BacktestResult:
    """Comprehensive performance metrics returned by VectorizedBacktester."""
    strategy_id: str
    species: StrategySpecies
    sharpe_ratio: float
    sortino_ratio: float
    calmar_ratio: float
    profit_factor: float
    max_drawdown: float                        # Decimal fraction (e.g. 0.08 = 8% drawdown)
    win_rate: float                            # Decimal fraction (e.g. 0.58 = 58% win rate)
    total_trades: int
    net_pnl_pct: float                         # Total return % (e.g. 24.5 = +24.5%)
    total_return: float                        # Ratio (e.g. 1.245)
    equity_curve: List[float] = field(default_factory=list)
    strategy_returns: Optional[np.ndarray] = None      # Per-bar net strategy returns array
    fitness_score: float = 0.0
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class TradeProposal:
    """Actionable trade proposal generated by candidate champion strategy."""
    strategy_id: str
    species: StrategySpecies
    action: str                                # "BUY", "SELL", "HOLD"
    symbol: str
    entry_price: float
    stop_loss_price: float
    take_profit_price: float                   # Target 1 (1.5R - 50% scale-out)
    target_2r_price: float = 0.0               # Target 2 (2.5R runner)
    invalidation_price: float = 0.0            # Structural key level invalidation
    execution_urgency: str = "PASSIVE_MAKER"   # "TAKER_AGGRESSIVE" or "PASSIVE_MAKER"
    confidence: float = 0.5                    # [0.0, 1.0]
    backtest_sharpe: float = 0.0
    win_rate: float = 0.0
    max_drawdown: float = 0.0
    profit_factor: float = 0.0
    genome: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class WalkForwardReport:
    """Out-of-sample validation metrics and overfitting audit."""
    strategy_id: str
    in_sample_sharpe: float
    out_of_sample_sharpe: float
    walk_forward_efficiency: float             # OOS Annualized Return / IS Annualized Return
    deflated_sharpe_ratio: float               # DSR probability (0.0 to 1.0, >0.95 = statistically significant)
    in_sample_pnl_pct: float
    out_of_sample_pnl_pct: float
    out_of_sample_max_drawdown: float
    out_of_sample_win_rate: float
    out_of_sample_trades: int
    is_overfit: bool
    kill_reason: Optional[str] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class MonteCarloReport:
    """Bootstrap permutation tail-risk analysis."""
    strategy_id: str
    permutations_tested: int
    drawdown_95th_percentile: float            # Expected worst-case drawdown in 95% of permutations
    max_drawdown_observed: float
    risk_of_ruin_pct: float                    # Probability of drawdown exceeding 20%
    probability_of_profit: float               # Probability of ending with positive PnL
    is_disqualified: bool
    rejection_reason: Optional[str] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


class RiskLevel(str, Enum):
    """5-tier institutional portfolio drawdown risk levels + recovery mode."""
    GREEN = "GREEN"          # Normal trading: DD < 3.0%, 100% position sizing
    YELLOW = "YELLOW"        # Warning: 3.0% <= DD < 5.0%, 50% position sizing
    ORANGE = "ORANGE"        # High Risk: 5.0% <= DD < 8.0%, 25% position sizing
    RED = "RED"              # Severe Risk: 8.0% <= DD < 10.0%, 0% new risk (closing only)
    CRITICAL = "CRITICAL"    # Emergency: DD >= 10.0%, Emergency Flatten all positions
    RECOVERY = "RECOVERY"    # Post-drawdown recovery: max 25% sizing until HWM exceeded


@dataclass
class RiskAssessment:
    """Comprehensive portfolio risk assessment generated by Risk Management Agent."""
    risk_level: RiskLevel                      # GREEN, YELLOW, ORANGE, RED, CRITICAL, RECOVERY
    portfolio_equity: float                    # Mark-to-market equity in USD
    high_water_mark: float                     # Peak equity observed in USD
    drawdown_pct: float                        # Current peak-to-trough drawdown (0.0 to 1.0)
    daily_loss_pct: float                      # Current daily loss from UTC midnight
    daily_loss_remaining_pct: float            # Distance remaining to daily 3% loss cap
    weekly_loss_pct: float                     # Current weekly loss from Monday UTC
    var_95_1day_usd: float                     # 95% 1-day Cornish-Fisher VaR in USD
    cvar_95_1day_usd: float                    # 95% 1-day Expected Shortfall in USD
    current_exposure_pct: float                # % of portfolio currently deployed in active positions
    max_exposure_allowed_pct: float            # Maximum permissible gross exposure (20% to 50%)
    consecutive_losses: int                    # Current consecutive losing trade count
    circuit_breaker_active: bool               # True if any loss limit or drawdown tripped
    circuit_breaker_reason: Optional[str] = None  # Reason string if tripped
    cooldown_until: Optional[datetime] = None  # Timestamp until cooldown expires
    is_proposal_approved: bool = True          # ABSOLUTE VETO FLAG: True = Allowed, False = Rejected
    rejection_reason: Optional[str] = None     # Explicit gate failure reason
    allowed_size_multiplier: float = 1.0       # Downscales position (1.0, 0.5, 0.25, 0.0)
    dollar_risk_cap_usd: float = 0.0           # Maximum allowable dollar loss on this trade (1.5% of equity)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "risk_level": self.risk_level.value if isinstance(self.risk_level, RiskLevel) else str(self.risk_level),
            "portfolio_equity": round(self.portfolio_equity, 2),
            "high_water_mark": round(self.high_water_mark, 2),
            "drawdown_pct": round(self.drawdown_pct, 4),
            "daily_loss_pct": round(self.daily_loss_pct, 4),
            "daily_loss_remaining_pct": round(self.daily_loss_remaining_pct, 4),
            "weekly_loss_pct": round(self.weekly_loss_pct, 4),
            "var_95_1day_usd": round(self.var_95_1day_usd, 2),
            "cvar_95_1day_usd": round(self.cvar_95_1day_usd, 2),
            "current_exposure_pct": round(self.current_exposure_pct, 4),
            "max_exposure_allowed_pct": round(self.max_exposure_allowed_pct, 4),
            "consecutive_losses": int(self.consecutive_losses),
            "circuit_breaker_active": bool(self.circuit_breaker_active),
            "circuit_breaker_reason": self.circuit_breaker_reason,
            "cooldown_until": self.cooldown_until.isoformat() if self.cooldown_until else None,
            "is_proposal_approved": bool(self.is_proposal_approved),
            "rejection_reason": self.rejection_reason,
            "allowed_size_multiplier": round(self.allowed_size_multiplier, 2),
            "dollar_risk_cap_usd": round(self.dollar_risk_cap_usd, 2),
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class MoneyDecision:
    """Position sizing and capital allocation decision generated by Money Management Agent (Agent #7)."""
    strategy_id: str
    symbol: str
    action: str                                # "BUY", "SELL"
    position_size_usd: float                   # Recommended position size in USD
    position_size_asset: float                 # Recommended position size in base currency (e.g. BTC)
    kelly_fraction_used: float                 # e.g. 0.50 for Half-Kelly
    kelly_full_pct: float                      # Unleveraged full Kelly fraction %
    kelly_suggested_pct: float                 # Sized fraction % after Half-Kelly
    risk_adjusted_size_pct: float              # Final position size as % of portfolio equity
    dollar_risk_at_stop: float                 # Worst-case loss in USD if stop loss triggers
    dollar_risk_pct: float                     # Dollar loss as % of portfolio equity (<= 1.5%)
    fee_estimate_usd: float                    # Estimated round-trip fees + slippage in USD
    fee_drag_ratio: float                      # Expected profit USD / Estimated fee USD (must be >= 3.0)
    is_sizing_approved: bool                   # True if all budget, size, and fee gates pass
    rejection_reason: Optional[str] = None     # Reason if sizing rejected
    reserve_capital_usd: float = 0.0           # Protected reserve capital (40%)
    available_capital_usd: float = 0.0         # Deployable capital for new trades (60% max)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "action": self.action,
            "position_size_usd": round(self.position_size_usd, 2),
            "position_size_asset": round(self.position_size_asset, 6),
            "kelly_fraction_used": round(self.kelly_fraction_used, 2),
            "kelly_full_pct": round(self.kelly_full_pct, 4),
            "kelly_suggested_pct": round(self.kelly_suggested_pct, 4),
            "risk_adjusted_size_pct": round(self.risk_adjusted_size_pct, 4),
            "dollar_risk_at_stop": round(self.dollar_risk_at_stop, 2),
            "dollar_risk_pct": round(self.dollar_risk_pct, 4),
            "fee_estimate_usd": round(self.fee_estimate_usd, 2),
            "fee_drag_ratio": round(self.fee_drag_ratio, 2),
            "is_sizing_approved": bool(self.is_sizing_approved),
            "rejection_reason": self.rejection_reason,
            "reserve_capital_usd": round(self.reserve_capital_usd, 2),
            "available_capital_usd": round(self.available_capital_usd, 2),
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class FinalTradeDecision:
    """Boardroom consensus decision generated by Trade Decider Agent (Agent #8)."""
    strategy_id: str
    symbol: str
    action: str                                # "BUY", "SELL", "HOLD"
    decision: str                              # "APPROVED", "DOWNSIZED", "REJECTED"
    consensus_score: float                     # Weighted score across all agents [0.0, 1.0]
    consensus_threshold: float                 # Required threshold to approve (default 0.65)
    agent_votes: Dict[str, Dict[str, Any]]     # Breakdown of each agent's normalized score, weight, and status
    vetoes_triggered: List[str]                # List of any active veto reasons
    conflicts_detected: List[str]              # List of inter-agent contradictions
    approved_position_size_usd: float          # Final approved size in USD
    approved_position_size_asset: float        # Final approved size in base asset
    entry_price: float                         # Limit or market entry price
    stop_loss_price: float                     # Stop loss price
    take_profit_target_1: float                # 1.5R target (50% scale-out)
    take_profit_target_2: float                # 2.5R target (runner)
    invalidation_price: float                  # Structural key level invalidation
    execution_urgency: str                     # "PASSIVE_MAKER", "TAKER_AGGRESSIVE"
    decision_reasoning: str                    # Summary explanation of boardroom consensus
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "action": self.action,
            "decision": self.decision,
            "consensus_score": round(self.consensus_score, 4),
            "consensus_threshold": round(self.consensus_threshold, 2),
            "agent_votes": self.agent_votes,
            "vetoes_triggered": self.vetoes_triggered,
            "conflicts_detected": self.conflicts_detected,
            "approved_position_size_usd": round(self.approved_position_size_usd, 2),
            "approved_position_size_asset": round(self.approved_position_size_asset, 6),
            "entry_price": round(self.entry_price, 2),
            "stop_loss_price": round(self.stop_loss_price, 2),
            "take_profit_target_1": round(self.take_profit_target_1, 2),
            "take_profit_target_2": round(self.take_profit_target_2, 2),
            "invalidation_price": round(self.invalidation_price, 2),
            "execution_urgency": self.execution_urgency,
            "decision_reasoning": self.decision_reasoning,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class OrderIntent:
    """Actionable order intent dispatched to Trade Executor Agent (Agent #9)."""
    intent_id: str
    symbol: str
    side: str                                  # "BUY", "SELL"
    order_type: str                            # "LIMIT", "MARKET"
    quantity_asset: float                      # Order quantity in base asset (e.g. BTC)
    notional_usd: float                        # Order notional in USD
    limit_price: float                         # Limit price (or reference price for market)
    stop_loss_price: float                     # Server-side stop loss order price
    take_profit_price: float                   # Take profit limit order price
    target_2r_price: float                     # Trailing target price
    invalidation_price: float                  # Key level cancellation threshold
    urgency: str                               # "PASSIVE_MAKER", "TAKER_AGGRESSIVE"
    leverage: float = 1.0                      # Max 2x or 1x spot
    client_order_id: Optional[str] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "side": self.side,
            "order_type": self.order_type,
            "quantity_asset": round(self.quantity_asset, 6),
            "notional_usd": round(self.notional_usd, 2),
            "limit_price": round(self.limit_price, 2),
            "stop_loss_price": round(self.stop_loss_price, 2),
            "take_profit_price": round(self.take_profit_price, 2),
            "target_2r_price": round(self.target_2r_price, 2),
            "invalidation_price": round(self.invalidation_price, 2),
            "urgency": self.urgency,
            "leverage": round(self.leverage, 1),
            "client_order_id": self.client_order_id,
            "timestamp": self.timestamp.isoformat(),
        }


# ==============================================================================
# SPRINT 9: TRADE EXECUTION & BRACKET ORDER CONTRACTS
# ==============================================================================

class ExecutionMode(str, Enum):
    """Trading execution target environment."""
    PAPER = "PAPER"
    LIVE_TESTNET = "LIVE_TESTNET"
    LIVE_PRODUCTION = "LIVE_PRODUCTION"


class OrderStatus(str, Enum):
    """Status lifecycle of an exchange order."""
    PENDING_SUBMIT = "PENDING_SUBMIT"
    OPEN = "OPEN"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class OrderRole(str, Enum):
    """Role within the multi-tier bracket order architecture."""
    PARENT_ENTRY = "PARENT_ENTRY"
    STOP_LOSS = "STOP_LOSS"
    TAKE_PROFIT_1 = "TAKE_PROFIT_1"
    TAKE_PROFIT_2 = "TAKE_PROFIT_2"
    EMERGENCY_FLATTEN = "EMERGENCY_FLATTEN"


@dataclass
class ExecutionReport:
    """Detailed audit report of an executed or updated order."""
    order_id: str
    client_order_id: str
    intent_id: str
    symbol: str
    side: str                                  # "BUY", "SELL"
    order_type: str                            # "LIMIT", "MARKET"
    role: OrderRole
    status: OrderStatus
    requested_price: float
    fill_price: float
    requested_qty: float
    filled_qty: float
    fee_paid_usd: float
    slippage_bps: float                        # Slippage relative to requested limit/market price
    latency_ms: float                          # Processing & round-trip network latency in milliseconds
    execution_mode: ExecutionMode = ExecutionMode.PAPER
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "order_id": self.order_id,
            "client_order_id": self.client_order_id,
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "side": self.side,
            "order_type": self.order_type,
            "role": self.role.value,
            "status": self.status.value,
            "requested_price": round(self.requested_price, 2),
            "fill_price": round(self.fill_price, 2),
            "requested_qty": round(self.requested_qty, 6),
            "filled_qty": round(self.filled_qty, 6),
            "fee_paid_usd": round(self.fee_paid_usd, 4),
            "slippage_bps": round(self.slippage_bps, 2),
            "latency_ms": round(self.latency_ms, 2),
            "execution_mode": self.execution_mode.value,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class ActivePosition:
    """Live open inventory tracking with stop/target linkage."""
    position_id: str
    strategy_id: str
    symbol: str
    side: str                                  # "LONG", "SHORT"
    entry_price: float
    quantity: float
    notional_usd: float
    current_mark_price: float
    unrealized_pnl_usd: float
    unrealized_pnl_pct: float
    stop_loss_price: float
    take_profit_price_1: float                 # 1.5R target
    take_profit_price_2: float                 # 2.5R target
    parent_order_id: str
    stop_order_id: Optional[str] = None
    tp1_order_id: Optional[str] = None
    tp2_order_id: Optional[str] = None
    is_scale_out_executed: bool = False
    is_breakeven_active: bool = False
    opened_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    max_hold_candles: int = 72  # 72 x 1h = 3 days max hold time

    def to_dict(self) -> Dict[str, Any]:
        return {
            "position_id": self.position_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "side": self.side,
            "entry_price": round(self.entry_price, 2),
            "quantity": round(self.quantity, 6),
            "notional_usd": round(self.notional_usd, 2),
            "current_mark_price": round(self.current_mark_price, 2),
            "unrealized_pnl_usd": round(self.unrealized_pnl_usd, 2),
            "unrealized_pnl_pct": round(self.unrealized_pnl_pct, 4),
            "stop_loss_price": round(self.stop_loss_price, 2),
            "take_profit_price_1": round(self.take_profit_price_1, 2),
            "take_profit_price_2": round(self.take_profit_price_2, 2),
            "parent_order_id": self.parent_order_id,
            "stop_order_id": self.stop_order_id,
            "tp1_order_id": self.tp1_order_id,
            "tp2_order_id": self.tp2_order_id,
            "is_scale_out_executed": self.is_scale_out_executed,
            "is_breakeven_active": self.is_breakeven_active,
            "opened_at": self.opened_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
        }


@dataclass
class BracketOrderGroup:
    """Container managing the lifecycle and OCO linkage of an active bracket order set."""
    bracket_id: str
    intent_id: str
    symbol: str
    parent_order_id: str
    parent_status: OrderStatus
    stop_order_id: Optional[str] = None
    stop_status: Optional[OrderStatus] = None
    tp1_order_id: Optional[str] = None
    tp1_status: Optional[OrderStatus] = None
    tp2_order_id: Optional[str] = None
    tp2_status: Optional[OrderStatus] = None
    is_oco_active: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "bracket_id": self.bracket_id,
            "intent_id": self.intent_id,
            "symbol": self.symbol,
            "parent_order_id": self.parent_order_id,
            "parent_status": self.parent_status.value,
            "stop_order_id": self.stop_order_id,
            "stop_status": self.stop_status.value if self.stop_status else None,
            "tp1_order_id": self.tp1_order_id,
            "tp1_status": self.tp1_status.value if self.tp1_status else None,
            "tp2_order_id": self.tp2_order_id,
            "tp2_status": self.tp2_status.value if self.tp2_status else None,
            "is_oco_active": self.is_oco_active,
        }




